FROM manjarolinux/base:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
      clang \
      lld \
      cmake \
      ninja \
      git \
      openssh \
      sshpass \
      autoconf \
      automake \
      libtool \
      make \
      boost \
      icu \
      sqlite3 \
      zlib && \
    pacman -Scc --noconfirm

WORKDIR /app
