FROM manjarolinux/base:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
      clang \
      lld \
      cmake \
      ninja \
      git \
      openssh \
      autoconf \
      automake \
      libtool \
      make \
    && pacman -Scc --noconfirm

WORKDIR /app
